# Generated by Django 2.2 on 2020-06-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('inquiry_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ignore'), (2, 'Completed')], default=0, max_length=1, verbose_name='inquiry_status')),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
    ]
