# Generated by Django 2.2 on 2020-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(choices=[(0, 'Andrew'), (1, 'William'), (2, 'Emma')], max_length=20, verbose_name='person_in_charge')),
                ('pic_email', models.EmailField(max_length=255, verbose_name='pic_email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('inquiry_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ignore'), (2, 'Completed')], default=0, max_length=1, verbose_name='inquiry_status')),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'inquiry_comment',
            },
        ),
    ]
