# Generated by Django 2.2 on 2020-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_apps', '0003_auto_20200629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirycomment',
            name='pic',
            field=models.IntegerField(choices=[(0, 'Andrew'), (1, 'William'), (2, 'Emma')], max_length=20, verbose_name='person_in_charge'),
        ),
    ]
