# Generated by Django 2.2 on 2020-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_apps', '0005_auto_20200802_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('avator', models.ImageField(default='images/default_icon.png', upload_to='media/', verbose_name='avator')),
                ('birthday', models.DateField(null=True, verbose_name='birthday')),
            ],
        ),
    ]
